name: Docker

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - '**'
    paths:
      - docker-bake.hcl
      - Dockerfile
      - requirements.txt
      - .github/workflows/docker.yml


jobs:
  Bake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bake-target: ["3.6-release", "3.7-release", "3.8-release", "3.9-release"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login To GitHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Login To GitLab
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USER }}
        password: ${{ secrets.GITLAB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3.4.0
      with:
        images: cyb3rjak3/alpine-pandas,ghcr.io/cyb3r-jak3/alpine-pandas,registry.gitlab.com/cyb3r-jak3/alpine-pandas
        flavor: |
          latest=false
        tags: |
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/docker-alpine-pandas.git
          org.label-schema.schema-version=1.0.0-rc1
          maintainer=Cyb3r Jak3 jake@jwhite.network
          org.opencontainers.image.vendor=cyb3rjak3


    - name: Build
      uses: docker/bake-action@v1.5.0
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: ${{ matrix.bake-target }}
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        pull: true